### ISSUE TITLE
Socket closed with transport error "Error: not opened"

### ISSUE THREAD

**Issue by timjrobinson** [socketio/engine.io#307]
I recently updated my app from engine.io 1.3.3 to 1.5.1 and have started seeing the following error which I haven't seen before. Any ideas what could be causing it:

I got this listening on the "close" event for the socket. 

Reason: transport error
Description:
```
Error: not opened
at WebSocket.send (/home/ubuntu/newclient/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:198:38)
at /home/ubuntu/newclient/node_modules/engine.io/lib/transports/websocket.js:91:19
at Object.exports.encodePacket (/home/ubuntu/newclient/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:81:10)
at WebSocket.send (/home/ubuntu/newclient/node_modules/engine.io/lib/transports/websocket.js:88:12)
at Socket.flush (/home/ubuntu/newclient/node_modules/engine.io/lib/socket.js:341:20)
at WebSocket.emit (events.js:117:20)
at /home/ubuntu/newclient/node_modules/engine.io/lib/transports/websocket.js:94:14
at afterWrite (_stream_writable.js:277:3)
at _stream_writable.js:266:9
at process._tickDomainCallback (node.js:463:13)
```

**Comment by nkzawa** [comment]
This happens when you try to send a message when underlying websocket is closing.

**Comment by darrachequesne** [comment]
Closed due to inactivity. Please reopen if needed.

**Comment by lyn0032** [comment]
just try..catch it
