### ISSUE TITLE
Koa framework support?

### ISSUE THREAD

**Issue by ilearnio** [socketio/engine.io#359]
Hi, I'm trying to connect Engine.io over Primus to Koa framework, which seems pretty similar to Express, but something was giving me an error. I tried to figure out what exactly was causing it, and it turns out that it was Engine.io. In the browser it gives
```
WebSocket connection to 'ws://localhost:3000/primus/?_primuscb=L1bdrMr' failed: Connection closed before receiving a handshake response
```

And on the server:
```
unknown transport "undefined"

Trace
    at Server.verify (/Users/Admin/Code/www/app/node_modules/engine.io/lib/server.js:108:11)
    at Server.handleUpgrade (/Users/Admin/Code/www/app/node_modules/engine.io/lib/server.js:276:8)
    at child.upgrade (/Users/Admin/Code/www/app/node_modules/primus/transformers/engine.io/server.js:52:18)
    at child.emit (/Users/Admin/Code/www/app/node_modules/eventemitter3/index.js:91:35)
    at emitter (/Users/Admin/Code/www/app/node_modules/emits/index.js:26:22)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:125:24)
    at done (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:139:7)
    at Primus.client (/Users/Admin/Code/www/app/node_modules/primus/middleware/authorization.js:19:49)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:136:14)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:126:60)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:126:60)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:126:60)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:126:60)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:126:60)
    at iterate (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:132:14)
    at child.forEach (/Users/Admin/Code/www/app/node_modules/primus/transformer.js:141:4)
```

Any plans to add support for Koa? Thanks

**Comment by ilearnio** [comment]
My server code looks like that:
```javascript
import koa from 'koa';
import http from 'http';
import Primus from 'primus';
import render from 'koa-ejs';
import serve from 'koa-static';
import Router from 'koa-router';

const app = koa();

render(app, {
  root: 'public/client/apps',
  layout: '',
  viewExt: '',
  cache: false,
  debug: true
});

// public routes
var publicRouter = new Router();
publicRouter.get('/', function*(next) {
  yield this.render('/index.ejs', {
    title: 'Hello!',
    head: '',
    body_content: '',
    inline_scripts: ''
  });
});

app.use(serve('public', {}));

app.use(publicRouter.middleware());


const server = http.createServer(app.callback());
const primus = new Primus(server, {
  transformer: 'engine.io',
  parser: 'JSON'
});

primus.on('connection', function(spark) {
  if (spark) {
    spark.send('news', { hello: 'world' });
    spark.on('my other event', function (data) {
      console.log(data);
    });
  }
});

// start server
server.listen.call(server, process.env.PORT);

```

**Comment by ilearnio** [comment]
Sorry, my mistake :/ Closing
