### ISSUE TITLE
'WebSocketHybi' object has no attribute 'version'

### ISSUE THREAD

**Issue by chrisspen** [socketio/engine.io#383]
Attempting to run simple [Flask-SocketIO example](https://github.com/miguelgrinberg/Flask-SocketIO/) fails with the traceback:

    Traceback (most recent call last):
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/greenlet.py", line 390, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 571, in handle
        handler.handle()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 180, in handle
        result = self.handle_one_request()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 314, in handle_one_request
        self.handle_one_response()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 37, in handle_one_response
        return self._handle_websocket()
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 62, in _handle_websocket
        self.application(environ, self._fake_start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
        start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
        return self.engineio_app.handle_request(environ, start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/socketio/server.py", line 303, in handle_request
        return self.eio.handle_request(environ, start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/engineio/server.py", line 226, in handle_request
        environ, start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/engineio/socket.py", line 77, in handle_get_request
        start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/engineio/socket.py", line 116, in _upgrade_websocket
        return ws(environ, start_response)
      File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/engineio/async_gevent.py", line 39, in __call__
        self.version = self._sock.version
    AttributeError: 'WebSocketHybi' object has no attribute 'version'

Is this a misconfiguraion on my part or a bug in socketio?

My package versions are:

    Flask==0.10.1
    Flask-Login==0.3.2
    Flask-SocketIO==2.1
    gevent==0.13.8
    gevent-socketio==0.3.5rc2
    gevent-websocket==0.3.6
    greenlet==0.4.0
    itsdangerous==0.24
    python-engineio==0.8.8
    python-socketio==1.0
    Werkzeug==0.11.4

**Comment by nkzawa** [comment]
it's likely the issue of `Flask-SocketIO`. Please report it to their issue tracker. Feel feel to reopen.
