### ISSUE TITLE
In what cases would give out the [Maximum call stack size exceeded] error?

### ISSUE THREAD

**Issue by xidui** [socketio/engine.io#399]
RangeError: Maximum call stack size exceeded
    at Socket.flush (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/socket.js:413:32)
    at emitNone (events.js:85:20)
    at WebSocket.emit (events.js:179:7)
    at Array.<anonymous> (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/transports/websocket.js:109:14)
    at _stream_writable.js:383:15
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
RangeError: Maximum call stack size exceeded
    at Socket.flush (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/socket.js:413:32)
    at emitNone (events.js:85:20)
    at WebSocket.emit (events.js:179:7)
    at Array.<anonymous> (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/transports/websocket.js:109:14)
    at _stream_writable.js:383:15
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)

**Comment by JoneXie1986** [comment]
me too

**Comment by Andy-hpliu** [comment]
/node_modules/engine.io/lib/socket.js:338
      this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);
                               ^
me too
socket.io 1.4.8

RangeError: Maximum call stack size exceeded
    at Socket.flush (/home/gzliuhaiping/workspace/stf/stf-web/openstf/node_modules/engine.io/lib/socket.js:338:32)
    at emitNone (events.js:72:20)
    at WebSocket.emit (events.js:166:7)
    at /home/gzliuhaiping/workspace/stf/stf-web/openstf/node_modules/engine.io/lib/transports/websocket.js:94:14
    at afterWrite (_stream_writable.js:346:3)
    at nextTickCallbackWithManyArgs (node.js:477:18)
    at process._tickCallback (node.js:375:17)

**Comment by furiousOyster** [comment]
It seems that if you do not allow the main thread to take a break and process the queued up IO, then you will receive this error as the queues will overflow.  If you break out of your current op, by calling setTimeout() or some other means to yield execution momentarily, the buffers will be cleared.
This seems to be self limiting, in that if allowing the IO to flush correctly, there is no amount of load that you can create which will cause stack size exceptions like these.

**Comment by darrachequesne** [comment]
`RangeError: Maximum call stack size exceeded` can happen when the array `this.packetsFn` is too big (too many arguments):

```js
[].push.apply([], new Array(200000));
// throws 'RangeError: Maximum call stack size exceeded'
```
If it is actually the reason, it can be fixed with a for loop:
```js
this.sentCallbackFn.push.apply(this.sentCallbackFn, this.packetsFn);
// becomes
for (var i = 0; i < this.packetsFn.length; i++) {
  this.sentCallbackFn.push(this.packetsFn[i]);
};
```
