### ISSUE TITLE
Ping timeout test fails

### ISSUE THREAD

**Issue by alexhultman** [socketio/engine.io#412]
This ping test fails sometimes, it depends on way too small timeout of 10ms:

Uncaught Error: expected 'transport error' to equal 'ping timeout'

**Comment by alexhultman** [comment]
I've run tests in parallel in a loop and triggered the same ping time out error on both uws 0.4.0, uws 0.7.7 and ws. So it happens with both uws and ws.


As you can see here, the first test round (that is the ws test round) fails:
```
> engine.io@1.6.11 test /home/alexhultman/engine.io
> gulp test; EIO_WS_ENGINE=uws gulp test;

[05:59:24] Using gulpfile ~/engine.io/gulpfile.js
[05:59:24] Starting 'test'...


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  46 passing (2s)
  1 failing

  1) server close should trigger on both ends upon ping timeout:
     Uncaught Error: expected 'transport error' to equal 'ping timeout'
      at Assertion.assert (node_modules/expect.js/expect.js:99:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/expect.js:200:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/expect.js:73:24)
      at Socket.onClose (test/server.js:424:29)
      at Socket.Emitter.emit (node_modules/component-emitter/index.js:134:20)
      at Socket.onClose (node_modules/engine.io-client/lib/socket.js:705:10)
      at Socket.onError (node_modules/engine.io-client/lib/socket.js:671:8)
      at XHR.<anonymous> (node_modules/engine.io-client/lib/socket.js:261:10)
      at XHR.Emitter.emit (node_modules/component-emitter/index.js:134:20)
      at XHR.Transport.onError (node_modules/engine.io-client/lib/transport.js:65:8)
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io/pull/461.
