### ISSUE TITLE
Max call stack error on high load

### ISSUE THREAD

**Issue by konstantinzolotarev** [socketio/engine.io#464]
### Current behaviour
In several minutes received about 50k new connections and from time to time see this in logs: 
```
/var/app/current/node_modules/engine.io/lib/socket.js:275
    cleanup();
    ^

RangeError: Maximum call stack size exceeded
    at Socket.clearTransport (/var/app/current/node_modules/engine.io/lib/socket.js:275:5)
    at Socket.onClose (/var/app/current/node_modules/engine.io/lib/socket.js:310:10)
    at Socket.onError (/var/app/current/node_modules/engine.io/lib/socket.js:120:8)
    at WebSocket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.Transport.onError (/var/app/current/node_modules/engine.io/lib/transport.js:91:10)
    at onEnd (/var/app/current/node_modules/engine.io/lib/transports/websocket.js:118:26)
    at Sender.frameAndSend (/var/app/current/node_modules/ws/lib/Sender.js:235:38)
    at /var/app/current/node_modules/ws/lib/Sender.js:126:12
```

### Steps to reproduce (if the current behaviour is a bug)
Actually no specific steps exist. App works pretty normally but from time to time see this in logs.

### Setup
- OS: Linux
- browser: -
- engine.io version: 1.8.2

**Comment by konstantinzolotarev** [comment]
And another 2 similar issues:

```
/var/app/current/node_modules/engine.io/lib/transport.js:88
    var err = new Error(msg);
              ^

RangeError: Maximum call stack size exceeded
    at new Error (native)
    at WebSocket.Transport.onError (/var/app/current/node_modules/engine.io/lib/transport.js:88:15)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.close (/var/app/current/node_modules/ws/lib/WebSocket.js:134:10)
    at WebSocket.doClose (/var/app/current/node_modules/engine.io/lib/transports/websocket.js:132:15)
    at WebSocket.Transport.close (/var/app/current/node_modules/engine.io/lib/transport.js:75:8)
    at Socket.clearTransport (/var/app/current/node_modules/engine.io/lib/socket.js:284:18)
    at Socket.onClose (/var/app/current/node_modules/engine.io/lib/socket.js:310:10)
    at Socket.onError (/var/app/current/node_modules/engine.io/lib/socket.js:120:8)
```

```
internal/process/next_tick.js:136
    this.domain = process.domain || null;
                         ^

RangeError: Maximum call stack size exceeded
    at new TickObject (internal/process/next_tick.js:136:26)
    at process.nextTick (internal/process/next_tick.js:154:24)
    at process.wrappedFunction [as nextTick] (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:284:51)
    at Socket.onClose (/var/app/current/node_modules/engine.io/lib/socket.js:305:13)
    at Socket.onError (/var/app/current/node_modules/engine.io/lib/socket.js:120:8)
    at WebSocket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.Transport.onError (/var/app/current/node_modules/engine.io/lib/transport.js:91:10)
    at onEnd (/var/app/current/node_modules/engine.io/lib/transports/websocket.js:118:26)
```

**Comment by lpinca** [comment]
@konstantinzolotarev see https://github.com/websockets/ws/issues/758.

**Comment by konstantinzolotarev** [comment]
@lpinca I think this issue could be closed. 
Because all future conversation and problems should be into websockets/ws#758

**Comment by lpinca** [comment]
@konstantinzolotarev agreed.
