### ISSUE TITLE
While upgrading: Cannot read property 'prototype' of undefined (Stracktrace)

### ISSUE THREAD

**Issue by laino** [socketio/engine.io#465]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/engine.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

Stacktrace during upgrade. See stracktrace.

### Steps to reproduce (if the current behaviour is a bug)

I believe some user is using an experimental client written in elixir.

### Expected behaviour

Doesn't crash.

### Setup
- OS:
- browser:
- engine.io version:

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

```
[11:12:41 PM Worker 46054 Critical] TypeError: Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at Server.onWebSocket (/var/volafile/app/node_modules/engine.io/lib/server.js:358:40)
    at /var/volafile/app/node_modules/engine.io/lib/server.js:343:12
    at completeHybiUpgrade2 (/var/volafile/app/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/var/volafile/app/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/var/volafile/app/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/var/volafile/app/node_modules/ws/lib/WebSocketServer.js:173:26)
    at /var/volafile/app/node_modules/engine.io/lib/server.js:342:13
    at Server.verify (/var/volafile/app/node_modules/engine.io/lib/server.js:142:12)
    at Server.handleUpgrade (/var/volafile/app/node_modules/engine.io/lib/server.js:331:8)
    at Server.<anonymous> (/var/volafile/app/node_modules/engine.io/lib/server.js:451:14)
```

**Comment by dongmaster** [comment]
How to reproduce this bug:
Things that are assumed: You know how to use a terminal.
1. Install [Elixir](http://elixir-lang.org/install.html)
2. We're gonna create a new Elixir project now. Go to the directory where you keep projects and such.
3. Execute the following commands in terminal:
```
$ mix new hello_world
$ cd hello_world
```

Open the mix.exs file in the hello_world directory and replace its contents with the following:
```elixir
defmodule HelloWorld.Mixfile do
  use Mix.Project

  def project do
    [app: :hello_world,
     version: "0.1.0",
     elixir: "~> 1.3",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [
      applications: [:logger, :crypto, :ssl]
    ]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:websocket_client, git: "https://github.com/jeremyong/websocket_client"}
    ]
  end
end
```

Execute the following commands in a terminal:
```
$ mix deps.get
```

Replace the contents of hello_world/lib/hello_world.ex with the following:
```elixir
defmodule HelloWorld do
  @behaviour :websocket_client_handler

  def start_link do
    :websocket_client.start_link("wss://volafile.io/api/", __MODULE__, [])
  end

  def init([], _conn_state) do
    :websocket_client.cast(self, {:text, "message 1"})
    {:ok, 2}
  end

  def websocket_handle({:pong, _}, _conn_state, state) do
    {:ok, state}
  end

  def websocket_handle({:text, msg}, _conn_state, 5) do
    IO.puts "Received message: #{msg}"
    {:close, "", "done"}
  end

  def websocket_handle({:text, msg}, _conn_state, state) do
    IO.puts "Received message: #{msg}"
    Process.sleep(1000)
    {:reply, {:text, "hello, this is message #{state}"}, state + 1}
  end

  def websocket_info(:start, _conn_state, state) do
    {:reply, {:text, "erlang message received"}, state}
  end

  def websocket_terminate(reason, _conn_state, state) do
    IO.puts "Websocket closed because of \"#{reason}\" at the state \"#{state}\""
    :ok
  end
end
```

Execute the following command in the hello_world directory:
```
$ iex -S mix
```

You will now be dropped into the Elixir REPL. Execute the following command in the REPL:
```
HelloWorld.start_link
```

A stacktrace should show in the REPL.
Do note that the URL is in the start_link function of the hello_world.ex file.

**Comment by darrachequesne** [comment]
Hi! That should be fixed in `1.8.2`. Related: https://github.com/socketio/socket.io/issues/2779
