### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by fenzaiway** [socketio/engine.io#683]
/Users/aa/Documents/work/dd/pass/static/node_modules/engine.io/build/server.js:16
const TEXT_DECODER = new TextDecoder();
                     ^

ReferenceError: TextDecoder is not defined
    at Object.<anonymous> (/Users/aa/Documents/work/dd/pass/static/node_modules/engine.io/build/server.js:16:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by fenzaiway** [comment]
来信已经收到，谢谢！--by Crazy Chester

**Comment by iowaguy** [comment]
I am also seeing this issue. Same situation: my pipeline that was previously working is now failing here. Adding `const { TextEncoder, TextDecoder } = require("util");` before the offending line in `server.js` seems to let the build continue.

**Comment by bmeijwaard** [comment]
Disabled NPM package `browser-sync` for the time being. This depends on `socket.io`, which depends on `engine.io`.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/6dd2bc4f68edd7575c3844ae8ceadde649be95b2, included in version [6.5.1](https://github.com/socketio/engine.io/releases/tag/6.5.1).

Thanks for the heads-up :+1:
